%% FILE SUMMARY
% Purpose: Inspect one demo experiment and visualize EE trajectory/speed/states over time.
% Last Updated: 2026-04-14.
% Dependencies: MATLAB; Curve Fitting Toolbox.
% MATLAB Version: Tested on MATLAB R2025b; scripts using Name=Value syntax are recommended for R2021a or newer.
% Data: CSV logs in data/magnetic_data/demo_experiment.
% Outputs: Time-domain and spatial trajectory figures for exploratory analysis.
% Run Notes: Change filename to evaluate another demo recording.

warning off
try
    if(test)
        disp("TEST MODE ON "+scriptName)
        addpath("data/session_01")
        filename = "data/session_01/demo_experiment/Demo_exp_02_18_20_43_44.csv";
        data = importfile(filename);
    end 
catch exception
    clc
    clear
    close all
    disp("TEST MODE OFF")
    currentPath = pwd;
    cd ..
    addpath("data/session_01")
    filename = "demo_experiment/Demo_exp_02_18_20_43_44.csv";
    data = importfile(filename);
    cd(currentPath)
end

%%

EE_position = data(:,8:10);
speed = data(:,5);
time = data(:,1);
time = time-time(1);
state = data(:,end);

timeMask = (time >= 30) & (time <= 78);
timeplot = time(timeMask);
timeplot = timeplot-timeplot(1);

nSamplFiltering = 300;
EE_pos_x = smooth(EE_position(timeMask,1),nSamplFiltering);
EE_pos_y = smooth(EE_position(timeMask,2),nSamplFiltering);
EE_pos_z = smooth(EE_position(timeMask,3),nSamplFiltering);

state_plot = state(timeMask);

figure
subplot(211)
hold on
plot(timeplot, EE_pos_x)
plot(timeplot, EE_pos_y)
plot(timeplot, EE_pos_z)
hold off
subplot(212)
plot(timeplot, state_plot)

%%

function dataImported = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DEMOEXP0218204344 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  DEMOEXP0218204344 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  Demoexp0218204344 = importfile("C:\Users\Federico\OneDrive\Lavoro ARIES\06 - Internships & Thesis\Giuliano Giampietro\Data Analysis\magnetic_data\demo_experiment\Demo_exp_02_18_20_43_44.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Feb-2025 22:42:44

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 59);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "mag_pos_x", "mag_pos_y", "mag_pos_z", "mag_orien_x", "mag_orien_y", "mag_orien_z", "ee_x", "ee_y", "ee_z", "v_ee_x", "v_ee_y", "v_ee_z", "F_ee_x", "F_ee_y", "F_ee_z", "s1_x", "s1_y", "s1_z", "s2_x", "s2_y", "s2_z", "s3_x", "s3_y", "s3_z", "s4_x", "s4_y", "s4_z", "n_s1_x", "n_s1_y", "n_s1_z", "n_s2_x", "n_s2_y", "n_s2_z", "n_s3_x", "n_s3_y", "n_s3_z", "n_s4_x", "n_s4_y", "n_s4_z", "ls_compute_time", "r2", "O_T_EE_1", "O_T_EE_2", "O_T_EE_3", "O_T_EE_4", "O_T_EE_5", "O_T_EE_6", "O_T_EE_7", "O_T_EE_8", "O_T_EE_9", "O_T_EE_10", "O_T_EE_11", "O_T_EE_12", "O_T_EE_13", "O_T_EE_14", "O_T_EE_15", "O_T_EE_16", "state"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
dataImported = readtable(filename, opts);

%% Convert to output type
dataImported = table2array(dataImported);
end