%% FILE SUMMARY
% Purpose: Compare completion-time behavior between guidance modalities across subjects.
% Last Updated: 2026-04-14.
% Dependencies: MATLAB; Statistics and Machine Learning Toolbox; local package dependencies/dabarplot.m.
% MATLAB Version: Tested on MATLAB R2025b; scripts using Name=Value syntax are recommended for R2021a or newer.
% Data: Participant CSV files in data/magnetic_data/experiments_mod_1 and experiments_mod_2.
% Outputs: Condition-wise time plots, summary bars, and paired statistical test results.
% Run Notes: File lists are manually curated to enforce participant alignment.

warning off
try
    if(test)
        disp("TEST MODE ON "+scriptName)
        addpath(genpath("data/session_01"))
    end 
catch exception
    clc
    clear
    close all
    disp("TEST MODE OFF")
    % Operations over path
    currentPath = pwd;
    cd ..
    addpath(genpath("data/session_01"))
    cd(currentPath)
end

addpath("dependencies")

%%

files = ["data_em1_S01.csv"
         "data_em1_S02.csv"
         "data_em1_S03.csv"
         "data_em1_S04.csv"
         "data_em1_S05.csv"
         "data_em1_S06.csv"
         "data_em1_S07.csv"
         "data_em1_S08.csv"
         "data_em1_S09.csv"];
files2 = ["data_em2_S01.csv"
          "data_em2_S02.csv"
          "data_em2_S03.csv"
          "data_em2_S04.csv"
          "data_em2_S05.csv"
          "data_em2_S06.csv"
          "data_em2_S07.csv"
          "data_em2_S08.csv"
          "data_em2_S09.csv"];

for i = 1:size(files,1)
    data = importGuidanceFile(files(i));

    time = data(:,1)-data(1,1);
    EEpos = data(:,8:10);

    struct.time(i) = time(end);
    figure
    plot(time,EEpos(:,3))
end

for i = 1:size(files2,1)
    data = importGuidanceFile(files2(i));

    time = data(:,1)-data(1,1);
    EEpos = data(:,8:10);

    struct.time2(i) = time(end);
    figure
    plot(time,EEpos(:,3))
end

times = struct.time;

figure
hold on
plot(struct.time,"o")
plot(struct.time2,"x")

figure
h = dabarplot([struct.time;struct.time2]');

try
    if(test)
        [p,h,stats] = ranksum(struct.time',struct.time2');
    end 
catch exception
    [p,h,stats] = ranksum(struct.time',struct.time2')
end

%%

function data = importGuidanceFile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  CHIARAEXP0908121702 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  CHIARAEXP0908121702 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  CHIARAexp0908121702 = importfile("C:\Users\Federico\OneDrive\Lavoro ARIES\06 - Phd &Internships & Thesis\Giuliano Giampietro\Data Analysis\magnetic_data\experiments_mod_1\CHIARA_exp_09_08_12_17_02.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Jun-2025 23:15:04

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 28);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "mag_pos_x", "mag_pos_y", "mag_pos_z", "mag_orien_x", "mag_orien_y", "mag_orien_z", "ee_x", "ee_y", "ee_z", "v_ee_x", "v_ee_y", "v_ee_z", "F_ee_x", "F_ee_y", "F_ee_z", "s1_x", "s1_y", "s1_z", "s2_x", "s2_y", "s2_z", "s3_x", "s3_y", "s3_z", "s4_x", "s4_y", "s4_z"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
data = readtable(filename, opts);

%% Convert to output type
data = table2array(data);
end

