%% FILE SUMMARY
% Purpose: Perform static magnetometer calibration and visualize ellipsoid correction per sensor.
% Last Updated: 2026-04-14.
% Dependencies: MATLAB; Sensor Fusion and Tracking Toolbox; Navigation Toolbox.
% MATLAB Version: Tested on MATLAB R2025b; scripts using Name=Value syntax are recommended for R2021a or newer.
% Data: Calibration CSV logs in data/session_fede_2_novembre.
% Outputs: Raw vs calibrated 3D sensor clouds and fitted ellipsoid
% overlays.s
% Run Notes: Switch calibration input file by editing the magData assignment lines.

warning off
try
    if(test)
        disp("TEST MODE ON "+scriptName)
        addpath(genpath("data/session_02"))
    end
catch exception
    clc
    clear
    close all
    disp("TEST MODE OFF")
    % operations over path
    currentPath = pwd;
    cd ..
    addpath(genpath("data/session_02"))
    cd(currentPath)
end

addpath("dependencies")

%%

magData = readCalibFile("StaticCalibData.csv");
% number of measured axes
measPerAxis = 3;
% number of sensored read
numSensors = round(size(magData,2)/measPerAxis);

sz = 4;
axLim = 90; % uT

try
    if(test)
        figure(Units="normalized",Position=[0.1 0.3 0.8 0.35])
        for i = 1:numSensors
            subplot(1,4,i)
            idx = (i-1)*measPerAxis+1;
            [A,b,expmfs] = magcal(magData(:,idx:idx+2));
            scatter3(magData(:,idx),magData(:,idx+1),magData(:,idx+2),sz,"r",'filled')
            plotEllipsoid(b, A*A, expmfs^2)
            C = (magData(:,idx:idx+2)-b)*A; % Calibrated data
            scatter3(C(:,1),C(:,2),C(:,3),sz,"b",'filled')
            plotEllipsoid([0 0 0], eye(3), expmfs^2);
            hold off
            view(45,30)
            xlabel("B_x")
            ylabel("B_y")
            zlabel("B_z")
            axis([-1 1 -1 1 -1 1]*axLim)
        end
    end
catch exception
    figure(Units="normalized",Position=[0.1 0.3 0.8 0.35])
    for i = 1:numSensors
        subplot(1,4,i)
        idx = (i-1)*measPerAxis+1;
        [A,b,expmfs] = magcal(magData(:,idx:idx+2));
        disp("Calibration Data for Sensor "+num2str(i))
        disp("A :")
        disp(A)
        disp("b :")
        disp(b)
        disp("eps :")
        disp(expmfs)
        hold on
        scatter3(magData(:,idx),magData(:,idx+1),magData(:,idx+2),sz,"r",'filled')
        plotEllipsoid(b, A*A, expmfs^2)
        C = (magData(:,idx:idx+2)-b)*A; % Calibrated data
        scatter3(C(:,1),C(:,2),C(:,3),sz,"b",'filled')
        plotEllipsoid([0 0 0], eye(3), expmfs^2)
        hold off
        view(45,30)
        xlabel("B_x")
        ylabel("B_y")
        zlabel("B_z")
        axis([-1 1 -1 1 -1 1]*axLim)
    end
end

%% Auxiliary Functions

function calibrationData = readCalibFile(filename, dataLines)
% Auto-generated by MATLAB on 03-Nov-2024 00:16:53

% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
calibrationData = readtable(filename, opts);

% Convert to output type
calibrationData = table2array(calibrationData);
end


function plotEllipsoid(center, R, c)
% Define the number of points for plotting
n = 50;

% Create a meshgrid of spherical coordinates
[u, v] = meshgrid(linspace(0, 2*pi, n), linspace(0, pi, n));

% Parametric equations for the unit sphere
x = cos(u) .* sin(v);
y = sin(u) .* sin(v);
z = cos(v);

% Scaling based on c
scale_factors = sqrt(c);  % Assuming c provides the size scaling

% Apply rotation and scaling to each point
X = scale_factors * (R(1,1)*x + R(1,2)*y + R(1,3)*z) + center(1);
Y = scale_factors * (R(2,1)*x + R(2,2)*y + R(2,3)*z) + center(2);
Z = scale_factors * (R(3,1)*x + R(3,2)*y + R(3,3)*z) + center(3);

% Plot the ellipsoid
surf(X, Y, Z,'FaceAlpha',0.3);
axis equal;
% xlabel('X');
% ylabel('Y');
% zlabel('Z');
% title('Ellipsoid');
shading interp;
end

